package main

/*
	!DO NOT EDIT THIS FILE!

	If you plan to create a golang plugin for Wireshark,
	you're looking at the wrong file.
	Take your chance with "wirego_template.go".

	You probably don't want to look at this file actually.
	Thust me.
*/
// extern int wirego_version_major();
// extern int wirego_version_minor();
// extern char* wirego_plugin_name();
// extern char* wirego_plugin_filter();
// extern int wirego_detect_int(char *);

import "C"

const (
	WIREGO_VERSION_MAJOR = 1
	WIREGO_VERSION_MINOR = 0
)

// Not used
func main() {}

//export wirego_version_major
func wirego_version_major() C.int {
	return WIREGO_VERSION_MAJOR
}

//export wirego_version_minor
func wirego_version_minor() C.int {
	return WIREGO_VERSION_MINOR
}

//export wirego_plugin_name
func wirego_plugin_name() *C.char {
	return C.CString(WIREGO_PLUGIN_NAME)
}

//export wirego_plugin_filter
func wirego_plugin_filter() *C.char {
	return C.CString(WIREGO_PLUGIN_FILTER)
}

//export wirego_detect_int
func wirego_detect_int(i *C.int) *C.char {
	filterName, filterValue := getDetectFilterInteger()

	if len(filterName) == 0 {
		*i = 0
		return nil
	}
	*i = C.int(filterValue)
	return C.CString(filterName)
}

// https://stackoverflow.com/questions/6125683/call-go-functions-from-c
