name: Wirego plugin build on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windows:
    name: Build
    runs-on: windows-2022
    env:
      PLATFORM: x64
      WIRESHARK_BASE_DIR: C:\Development
      CMAKE_PREFIX_PATH: D:\a\wireshark\Qt\6.2.3\msvc2019_64
      WIRESHARK_VERSION_EXTRA: -GithubActionBuild
    steps:
      - name: Choco install
        run: choco install -y --force --no-progress asciidoctorj xsltproc docbook-bundle nsis winflexbison3 cmake
      - name: Install strawberryperl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.30'
          distribution: strawberry
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 16.8
      - name: Set MSVC command prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Clone Wireshark
        uses: actions/checkout@v3
        with:
          repository: wireshark/wireshark
          path: ${{ github.workspace }}/wireshark
          ref: release-4.2        
      - name: Clone Wirego plugin
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/wireshark/plugins/epan/wirego
      - name: Mkdir
        run: mkdir build
      - name: Cmake
        run: cmake -DCMAKE_SYSTEM_VERSION="10.0.20348.0" -A x64 ..
        env:
          PLATFORM: x64
          WIRESHARK_BASE_DIR: C:/wireshark-libs
          QT5_BASE_DIR: C:/Qt/5.12.3/msvc2017_64
        working-directory: build
      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: >
          cmake -DCMAKE_SYSTEM_VERSION="10.0.20348.0" -A x64
          -DBUILD_wireshark=OFF
          -DCUSTOM_PLUGIN_SRC_DIR=${{ github.workspace }}/wireshark/plugins/epan/wirego
        working-directory: build
      - name: Build
        run: cmake --build . --config RelWithDebInfo -- plugins
        working-directory: build
      - name: Export plugin
        uses: actions/upload-artifact@v4
        with:
          name: WiregoPlugin-Windows
          path: /run/plugins/4.2/epan/wirego.so
          working-directory: build