name: Wirego plugin build on macos

on:
  push:
    branches: ["main"]
    paths: [".github/workflows/cmake-macos.yml", "wirego_bridge/**"]
  pull_request:
    branches: ["main"]
    paths: [".github/workflows/cmake-macos.yml", "wirego_bridge/**"]

jobs:
  macos:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        wireshark_version: ["4.2", "4.4"]
    steps:
      - name: Set output folder
        env:
          VERSION: ${{ matrix.wireshark_version }}
        run: echo "OUTPUT_PATH=${VERSION//./-}" >> $GITHUB_ENV

      - name: Install deps
        run: brew install c-ares glib libgcrypt pcre2 speexdsp zeromq

      - name: Clone Wirego plugin
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/wirego

      - name: Clone Wireshark
        uses: actions/checkout@v3
        with:
          repository: wireshark/wireshark
          path: ${{ github.workspace }}/wireshark
          ref: release-${{ matrix.wireshark_version }}

      - name: Create plugin link
        run: ln -s ${{ github.workspace }}/wirego/wirego_bridge ${{ github.workspace }}/wireshark/plugins/epan/wirego

      - name: Create output dir
        run: mkdir ${{ github.workspace }}/build

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: >
          cmake -B ${{ github.workspace }}/build
          -DBUILD_wireshark=OFF
          -DCUSTOM_PLUGIN_SRC_DIR=${{ github.workspace }}/wireshark/plugins/epan/wirego
          -S ${{ github.workspace }}/wireshark

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Release -- wirego

      - name: Debug ls
        run: ls -R ${{ github.workspace }}/build

      - name: Export plugin
        uses: actions/upload-artifact@v4
        env:
          VERSION: ${{ matrix.wireshark_version }}
          run: echo "OUTPUT_PATH=${VERSION//./-}" >> $GITHUB_ENV
        with:
          name: WiregoPlugin-macOS-for-Wireshark-${{ matrix.wireshark_version }}
          path: ${{ github.workspace }}/build/run/Wireshark.app/Contents/PlugIns/wireshark/${{ env.OUTPUT_PATH }}/epan/wirego.so
